### ISSUE TITLE
Write in port serial

### ISSUE THREAD

**Issue by hamidjalili59** [FengChendian/serial_port_win32#1]
Greeting
What should I do if I want to write something in the serial port?
Everything in the library is great ♥
Thanks

**Comment by FengChendian** [comment]
😨Sorry for that, I forgot add write method to this libaray. I will add this methond now! Please wait a moment

**Comment by FengChendian** [comment]
I have updated Write API and doc in [pub packages](https://pub.dev/packages/serial_port_win32). Now you can write something in the serial port.

This function has been tested in STM32 board.

**Comment by hamidjalili59** [comment]
Thanks for following up
