### ISSUE TITLE
port.readBytesOnListen make UI hang/freeze a few millisecond when data come

### ISSUE THREAD

**Issue by indrawow** [FengChendian/serial_port_win32#11]
Using this code,
`_port.readBytesOnListen(255, (Uint8List value) {
      debugPrint(value.toString());
    });
`
then, 
`_port.writeBytesFromUint8List(uint8Data);
`

UI freeze a few millisecond, is there something i missed?

**Comment by FengChendian** [comment]
I use a stream to read with duration. But _read is a sync processing due to Windows 32API.

 Maybe you can use async or compute to solve this problem.

**Comment by FengChendian** [comment]
Refer to PR #16 , maybe due to WaitForSingleObjec blocking.
