### ISSUE TITLE
Question: Is there any way I can get serial number, manufacturer name, PID and VID information.

### ISSUE THREAD

**Issue by nirmalaranawat** [FengChendian/serial_port_win32#13]
I am making an windows application which communicates with hardware connected over serial port ( via USB to Serial converter). I want to the application to connected to an com port automatically if it meets certain criteria (Serial number, Manufacturer ID etc.).

**Comment by nirmalaranawat** [comment]
Thank you for the links. I will explore C++ option as well as the lib serial port from flutter.

**Comment by FengChendian** [comment]
I will try to support the feature in next version. But I find that win32 package does't support SetupDiGetDeviceInstanceIdW for now.

Please refer to [issue](https://github.com/timsneath/win32/issues/495)
