### ISSUE TITLE
Cannot write on port

### ISSUE THREAD

**Issue by AhmedMannai10** [FengChendian/serial_port_win32#17]
I can get the ports, connect to them and read data. but I cannot write 
```writeBytesFromString```  and  ```writeBytesFromUint8List``` always returns false

![dart](https://user-images.githubusercontent.com/77109198/173035139-a8bdce73-3992-43ba-a221-da72a32a1a34.png)
.

**Comment by FengChendian** [comment]
Actually, write successed. It's due to overlapped mode. Write Operation will return 0 and GetLastErrir will retrun 997.
I wii fix it.

**Comment by AhmedMannai10** [comment]
Well Done.
Thank you so much👍
