### ISSUE TITLE
suddenly，getAvailablePorts() failed,can't open register.

### ISSUE THREAD

**Issue by NickYoung-max** [FengChendian/serial_port_win32#23]
serial_port_win32 version is 0.5.2

run flutter doctor:
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows
    [Version 10.0.19044.2728], locale zh-CN)
[√] Windows Version (Installed version of Windows is
    version 10 or higher)
[√] Android toolchain - develop for Android devices
    (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio
    Community 2022 17.2.6)
[√] Android Studio (version 2021.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

when run the code SerialPort.getAvailablePorts() thorw execption like below:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: can't open Register
#0      SerialPort._getRegistryKeyValue (package:serial_port_win32/src/serial_port.dart:483:9)
#1      SerialPort.getAvailablePorts (package:serial_port_win32/src/serial_port.dart:545:18)

your example code is the same.

**Comment by FengChendian** [comment]
zh-CN? 那我直接用中文好了。看起来是你的注册表打开失败了，你看看你的注册表里有没有HKEY_LOCAL_MACHINE？这个报错我还是第一次见。

**Comment by NickYoung-max** [comment]
> zh-CN? 那我直接用中文好了。看起来是你的注册表打开失败了，你看看你的注册表里有没有HKEY_LOCAL_MACHINE？这个报错我还是第一次见。

![image](https://user-images.githubusercontent.com/38856823/225839743-aa09349c-f57c-477a-b502-75efa915a9ae.png)
有的。不止我一台电脑是这样，我同事的也是一样的错误，以前是可以的

**Comment by FengChendian** [comment]
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: can't open Register

![image](https://user-images.githubusercontent.com/37545115/225848874-4026b952-c2cc-496c-bcdc-f19dd3a237ca.png)
你继续展开看看，有没有HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\SERIALCOMM这条路径？
这段报错是
```
```

**Comment by NickYoung-max** [comment]
很奇怪，突然就好了，还是0.5.2版本，刚才试了一下，不报错了，我也没做其它操作

**Comment by FengChendian** [comment]
那可能是有别的软件也在扫注册表。下次你看看错误码。我下个版本把Error Code输出加进去吧，主要win32的GetLastError函数是废的，还得加额外的变量存储返回值当时就没加。

**Comment by NickYoung-max** [comment]
> 那可能是有别的软件也在扫注册表。下次你看看错误码。我下个版本把Error Code输出加进去吧，主要win32的GetLastError函数是废的，还得加额外的变量存储返回值当时就没加。

还是有问题，好像返回是固定的，都是com6、com7，其它设备都没有返回。
开机的时候（没有链接usb设备）打开注册表就发现有com6、com7，插上其它设备，还是只有com6、com7
![image](https://user-images.githubusercontent.com/38856823/226241944-6afc715c-53df-4b46-9590-6de0aedde06d.png)，
调用SerialPort.getAvailablePorts();方法的时候只返回com6、com7，其它链接的设备没有返回。

**Comment by FengChendian** [comment]
你同事的问题好解决，看起来是上面没有任何串口设备，所以没有SERIALCOMM文件夹，这个我加了个错误处理应该就能解决了。

你的话，应该是串口设备枚举失败，不是我库的问题。所有连接到Windows的虚拟串口（VCP）都会显示在这个注册表下。如果这里没有，说明是电脑没有识别到串口，或者你使用的不是由标准USB CDC协议实现的Virtual Com port。

**Comment by FengChendian** [comment]
1. 手机的话看你选什么， 你如果选传输文件，应该是能读到一个串口的，选MIDI、仅充电之类的不会有。
2. 打印机在我这边的电脑上是归类为HID设备的，不会在SERIALCOMM文件夹下。

PS: 一般读卡器肯定能读到，RFID一般都是输出SPI协议或者UART，后面会接个TTL转USB模块，这实现的就是串口功能。

**Comment by NickYoung-max** [comment]
好的，感谢!
