### ISSUE TITLE
Read COM port is missing message

### ISSUE THREAD

**Issue by maiducgiang** [FengChendian/serial_port_win32#24]
In my Flutter project windows, I connect COM with setting:
port = SerialPort(namePort,
          openNow: true,
          BaudRate: baudRate,
          Parity: parity,
          StopBits: stopBits,
          ByteSize: byteSize,
          ReadIntervalTimeout: readIntervalTimeout,
          ReadTotalTimeoutConstant: readTotalTimeoutConstant,
          ReadTotalTimeoutMultiplier: readTotalTimeoutMulti);
      port?.readBytesSize = 50;
 when i make the COM data return listener the data is sometimes lost a few bytes
 
![image](https://user-images.githubusercontent.com/43919583/230846070-22728afb-1ed0-4190-98fa-c08ec0ad52cd.png)

Can anyone give me a solution?

**Comment by FengChendian** [comment]
Do you insert `'\0'` at the end of char buffer?. 
And why you read many times after sent? Can you give me some ESP CODE about serial port?

**Comment by FengChendian** [comment]
The bug is due to `PurgeComm` should be executed before read. But purge operation may be processed after read. So messae is lost. 

Please try `1.1.0`. The bug should be fixed. If there is still bug, please reopen this issue.
