### ISSUE TITLE
reader.listen

### ISSUE THREAD

**Issue by hamidjalili59** [FengChendian/serial_port_win32#3]
hi bro 👋😅
can you implement a stream for read data and a method onErr or onDone 🙏
For example,🤔 when the port is disconnected from the system, the error method is executed🌹

**Comment by FengChendian** [comment]
Ok, I will finish it tomorrow(UTC+8)

**Comment by FengChendian** [comment]
done, maybe... I don't have time to test it today.

**Comment by FengChendian** [comment]
I will add listen to write and test it in the next few days

**Comment by sabin26** [comment]
@FengChendian readBytesOnListen is not working for me.
Reading data using other programs from c++  and also using with other flutter packages works as expected. But, using this package with same configurations  is not working for reading. Writing is working as expected ! Please have a look asap.

**Comment by FengChendian** [comment]
> 
> 
> @FengChendian readBytesOnListen is not working for me.
> Reading data using other programs from c++ and also using with other flutter packages works as expected. But, using this package with same configurations is not working for reading. Writing is working as expected ! Please have a look asap. I am getting empty data [ ].
> I tried the following code:
> `port.readBytesOnListen(256, (value) => print(value), onListen: () {},);`
> Here, value is returning [ ] first time and it is not updating when data is received again.
> 
> Is it not the function to constantly listen to receiving data ?

Yeah... The function was called only once. Because I close the subscription when function was called.

**Comment by FengChendian** [comment]
@sabin26 Maybe I should call it readBytesWithFunction.. .I achieve it for doing something when reading bytes. If you want to get data after reading, you should use onData, not onListen. 

Sorry about that, It was my fault that caused the misunderstanding

**Comment by sabin26** [comment]
@FengChendian Yes. If there is an API to listen receiving data then this package would cover most use cases. I am blocked in my project because of the unavailability of this function. I hope the API to be implemented soon.

**Comment by sabin26** [comment]
@FengChendian I looked into event driven method for being notified when the data arrives and found the use of 'WaitCommEvent'. I have no experience in win32 else I would have written the code and submitted a PR to this repository. I am going to place some links that might be useful.

https://docs.microsoft.com/en-us/previous-versions/ms810467(v=msdn.10)?redirectedfrom=MSDN#serial-status
https://docs.microsoft.com/en-us/windows/win32/devio/monitoring-communications-events
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-waitcommevent

I can confirm that, the required classes are available on the flutter win32 packages.

If your are able to understand and write code for its API, it would be really appreciated.
Also, Could you please at-least provide when will it be available ? I have been delaying my project.

**Comment by FengChendian** [comment]
> 
> 
> @FengChendian I looked into event driven method for being notified when the data arrives and found the use of 'WaitCommEvent'. I have no experience in win32 else I would have written the code and submitted a PR to this repository. I am going to place some links that might be useful.
> 
> https://docs.microsoft.com/en-us/previous-versions/ms810467(v=msdn.10)?redirectedfrom=MSDN#serial-status
> https://docs.microsoft.com/en-us/windows/win32/devio/monitoring-communications-events
> https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-waitcommevent
> 
> I can confirm that, the required classes are available on the flutter win32 packages.
> 
> If your are able to understand and write code for its API, it would be really appreciated.
> Also, Could you please at-least provide when will it be available ? I have been delaying my project.

I can try this tomorrow. Now I don't have any Serial Port device, because I can't go back to school due to the epidemic in Nanjing, China. So progress is slow. I will try to configure the virtual serial port to implement these method.

**Comment by FengChendian** [comment]
@sabin26 I didn't find **CreateEvent** function in win32 flutter package. So I violently achieved this function... 😂
I'm tesing this function. I think that it can call onData automatically if data is recevied...

Here is source code:
```dart
  void readBytesOnlisten(int bytesSize, Function(Uint8List value) onData) {
    if (_timer != null) {
      _timer!.cancel();
    }
    _timer = Timer.periodic(Duration(milliseconds: 20), (timer) {
      readBytes(bytesSize).then((value) {
        if (value.isEmpty) {
          return;
        }
        onData(value);
      });
    });
  }
```

**Comment by FengChendian** [comment]
@sabin26 done, you can test it using
```dart
port.readBytesOnListen(8, (value) => print(value));
```

Print will be called when receiving value/

**Comment by sabin26** [comment]
I saw this method but with byteSize 1 through your other repository: SerialPortTool. You did the exact same thing there. I will test it out.

**Comment by FengChendian** [comment]
> 
> 
> I saw this method but with byteSize 1 through your other repository: SerialPortTool. You did the exact same thing there. I will test it out.

Yeah... I use timer to implement read listen in my small project. Beacuse I don’t know whether Stream has a suitable API. 
I use byteSize 1 to refresh fast.

**Comment by sabin26** [comment]
@FengChendian Is it the bytesize or the timer of 20ms, I am getting wrong data sometimes. Should I drop my bytesize to 1 to refresh fast ?
Also, sometimes hex.encode(value) is returning me d0.10. The expected value should have been 00.10. I don't want aphabets. Do you know how to solve this ?

**Comment by sabin26** [comment]
Through my usage, I found that waiting for the bytes to arrive from the event as done in C++ or C# is the perfect way to solve the issue rather than looping the reading method continuously. So, I will be shifting my work to c# from flutter at-least for my current desktop project.
I appreciate your efforts made related to solving this issue.

**Comment by FengChendian** [comment]
@sabin26 Now library 0.2.2 API is
 ```dart
void readBytesOnListen(int bytesSize, Function(Uint8List value) onData, {void onBefore()?, Duration? duration})
```
You can set proper dutation using parameters duration. 

About wrong data, I can't reproduce this bug. It works fine on my machine. 
![图片](https://user-images.githubusercontent.com/37545115/127512797-6f564ee4-045c-42ec-a543-8af6aed436b5.png)

And about reading method continuously, win32 package doesn't supports CreatEvent to implement event. I will comment on win32 package.

**Comment by sabin26** [comment]
I saw that your issue made a contributor submit a PR to win32 repo on adding the CreateEvent method. I will follow up on that and I hope when win32 will merge the PR, this package will update the readBytesOnListen API based on the new method. You can test out the PR and be ready to update when win32 will support it.

**Comment by FengChendian** [comment]
@sabin26 I saw it too. I will test out the PR and try to implement wait event to get data properly. I hope that win32 package will merge the PR later. Then I will update this package to support new API.

**Comment by sabin26** [comment]
@FengChendian The PR has been merged in the github repo of win32 package.

**Comment by FengChendian** [comment]
> @FengChendian The PR has been merged in the github repo of win32 package.

I saw it. I will update this package if I have time in next few days.

**Comment by sabin26** [comment]
@FengChendian Any updates ?

**Comment by FengChendian** [comment]
@sabin26 Sorry... I am busy with my subject this week. I will try to update tomorrow.

**Comment by FengChendian** [comment]
@sabin26 Emmmmm.... Maybe I have encountered some difficulties. 
I tested C++ code in win32 example.  I found some problems which I can't solve. I can't read anything when char received. Here is code:
```cpp
#include <windows.h>
#include <tchar.h>
#include <assert.h>
#include <stdio.h>
using namespace std;
void test()
{
	DWORD dwCommEvent;
	DWORD dwRead;
	char  chRead = 0;

	HANDLE hCom;

	hCom = CreateFile(TEXT("\\\\.\\COM6"),
		GENERIC_READ | GENERIC_WRITE,
		0,    // exclusive access 
		NULL, // default security attributes 
		OPEN_EXISTING,
		FILE_FLAG_OVERLAPPED,
		NULL
	);

	if (hCom == INVALID_HANDLE_VALUE)
	{
		// Handle the error. 
		printf("CreateFile failed with error %d.\n", GetLastError());
		return;
	}

	if (!SetCommMask(hCom, EV_RXCHAR))
	{
		return;
	}
	// Error setting communications event mask.

	for (; ; )
	{


		if (WaitCommEvent(hCom, &dwCommEvent, NULL))
		{
			if (ReadFile(hCom, &chRead, 1, &dwRead, NULL))
			{
				cout << "Read" << endl;
			}
			else
			{
				cout << "error, read:" << chRead << endl;
				continue;
			}
		}
		else
			// Error in WaitCommEvent.
			continue;
	}

}

int main()
{
	cout << "Hello CMake." << endl;
	test();
	return 0;
}

```

**Comment by FengChendian** [comment]
@sabin26 Done in version 0.3.0

**Comment by sabin26** [comment]
@FengChendian 
I was expecting the WaitCommEvent to emit an event when the data is received. But you are using while(true) function to continuous loop inside the readBytesOnListen function.

(My expectation is shown below in the form of an example)
```
var receivedData = "";

_serialPort.OnDataReceived = OnDataReceivedFunc; // or any other format 

OnDataReceivedFunc()
{
    // will be called whenever _serialPort receives any data
    var bytes = read(bytesToRead);
    // receivedData += ConvertToString(bytes);
}
```
The above example is just a representation of what I want to achieve with this readBytesOnListen function. The implementation can be a bit different.

Here is the screenshot of the first comment on the issue. It says implementing a stream for read data. I believe the 2nd line represents my scenario.
![image](https://user-images.githubusercontent.com/61322712/130352090-86d3e4e0-a68e-4080-a412-497dc9f2270c.png)

And I am sorry if my previous comments could not make you clear on what the issue was.

**Comment by FengChendian** [comment]
@sabin26 I use `while(true)` just because WaitCommEvent will be executed once  when called. If you want to emit events when data is received, you must call WaitCommEvent again and again. Otherwise the function `OnDataReceivedFunc` will only respond once.

And most importantly, UI blocking is due to `WaitCommEvent` itself, not infinite loop. As long as you call `WaitCommEvent`, the UI will block. I will use isolate to solve the problem

**Comment by FengChendian** [comment]
@sabin26 I re-read win32 Docs. I know the solution now. 
Firstly, openFile using FILE_FLAG_OVERLAPPED (**Async I/O**), so `WaitCommEvent ` will return value imediately. When RXCHAR, it will get ERROR_IO_PENDING and can use `ReadFile` function. The solution needs to use `CreateEvent`.

But win32 package does't not publish 2.2.6 version which contains` CreatEvent` Function. I can't update my package because win32 package is too big and my network is bad.......
```cpp
#include <windows.h>
#include <tchar.h>
#include <assert.h>
#include <stdio.h>

using namespace std;

void test()
{
	DWORD dwCommEvent;
	DWORD dwRead;
	char  chRead = 0;
	OVERLAPPED o;

	HANDLE hCom;

	hCom = CreateFile(TEXT("\\\\.\\COM6"),
		GENERIC_READ | GENERIC_WRITE,
		0,    // exclusive access 
		NULL, // default security attributes 
		OPEN_EXISTING,
		FILE_FLAG_OVERLAPPED,
		NULL
	);

	if (hCom == INVALID_HANDLE_VALUE)
	{
		// Handle the error. 
		printf("CreateFile failed with error %d.\n", GetLastError());
		return;
	}

	DCB dcbSerialParameters = { 0 };

	if (!GetCommState(hCom, &dcbSerialParameters))
	{
		printf("Failed to get current serial parameters\n");
	}
	else
	{
		dcbSerialParameters.BaudRate = CBR_115200;
		dcbSerialParameters.ByteSize = 8;
		dcbSerialParameters.StopBits = ONESTOPBIT;
		dcbSerialParameters.Parity = NOPARITY;
		dcbSerialParameters.fDtrControl = DTR_CONTROL_DISABLE;

		if (!SetCommState(hCom, &dcbSerialParameters))
		{
			printf("Could not set serial port parameters\n");
		}
		else
		{

			PurgeComm(hCom, PURGE_RXCLEAR | PURGE_TXCLEAR);
			Sleep(100);
		}
	}

	if (!SetCommMask(hCom, EV_RXCHAR))
	{
		return;
	}


	o.hEvent = CreateEvent(
		NULL,   // default security attributes 
		TRUE,   // manual-reset event 
		FALSE,  // not signaled 
		NULL    // no name
	);


	// Initialize the rest of the OVERLAPPED structure to zero.
	o.Internal = 0;
	o.InternalHigh = 0;
	o.Offset = 0;
	o.OffsetHigh = 0;

	assert(o.hEvent);


	// Error setting communications event mask.
	for (; ; )
	{


		if (WaitCommEvent(hCom, &dwCommEvent, &o))
		{
			if (ReadFile(hCom, &chRead, 1, &dwRead, NULL))
			{
				cout << "Read" << chRead << endl;
			}
			else
			{
				cout << "error, read:" << chRead << endl;
				continue;
			}
		}
		else
		{
			if (GetLastError() == ERROR_IO_PENDING)
			{
				cout << " ERROR_IO_PENDING" << endl;
				if (WaitForSingleObject(o.hEvent, 500) == WAIT_OBJECT_0)
				{
					ReadFile(hCom, &chRead, 1, &dwRead, &o);
					cout << "Read:" << chRead << endl;
				}

			}
			ResetEvent(o.hEvent);
			continue;
		}
	}

}

int main()
{
	cout << "Hello CMake." << endl;
	test();
	return 0;
}

```

**Comment by sabin26** [comment]
@FengChendian The package win32 has been updated to version 2.2.6 that contains CreateEvent function. I tried to modify `readBytesOnListen` as per your C++ code.
Here is the result:
```dart
  void readBytesOnListen(int bytesSize, Function(Uint8List value) onData, {void onBefore()?}) async {
    Uint8List uint8list;
    if (SetCommMask(handler!, 0x0001) == 0) {
      throw Exception("SetCommMask EV_RXCHAR failed");
    }
    if (onBefore != null) {
      onBefore();
    }
    await _computer.turnOn();

    OVERLAPPED o = OVERLAPPED();

    o.hEvent = CreateEvent(
        nullptr, // default security attributes
        TRUE, // manual-reset event
        FALSE, // not signaled
        nullptr // no name
        );

    // Initialize the rest of the OVERLAPPED structure to zero.
    o.Internal = 0;
    o.InternalHigh = 0;

    assert(o.hEvent != 0);

    for (;;) {
      if (await _computer.compute(wait, param: handler) == 1) {
        uint8list = await _read(bytesSize);
        if (uint8list.isNotEmpty) {
          onData(uint8list);
        }
      } else {
        if (GetLastError() == ERROR_IO_PENDING) {
          if (WaitForSingleObject(o.hEvent, 500) == WAIT_OBJECT_0) {
            uint8list = await _read(bytesSize);
            if (uint8list.isNotEmpty) {
              onData(uint8list);
            }
          }
        }
        ResetEvent(o.hEvent);
      }
    }
  }
```
But there are 3 objects that give the error as they are not available on win32 package (or you could say that I could not find it).
```dart
ERROR_IO_PENDING
WAIT_OBJECT_0
ResetEvent()
```
I removed the below given lines as they were also not available.
```dart
o.Offset = 0;
o.OffsetHigh = 0;
```

**Comment by FengChendian** [comment]
> Although the `compute` is called for `WaitEvent`, I believe that calling the for loop with `for(;;)` or while loop with `while(true)` on UI thread might cause an issue. It's just a hunch. 

I have tested compute function in version 4.0.1 on GitHub. There are no UI blocking when loop. Because most of time will be used to wait Event, which is isolated.

But if you use WaitEvent function in FILE_ATTRIBUTE_NORMAL, you can't close handle while waiting event. That's a serious problem.

Maybe there are some problems which I can't realize. But I think I can't find better solution for constantly listen now. Because of WaitEvent function, I can't use stream or timer. Data isn't iterable or periodical. And timeout is infinite in this function.

I think another solution is using overlapped mode in I/O. Win32 package has published version 2.2.6 today. I will test it and using stream or timer to implement listen.

**Comment by FengChendian** [comment]
@sabin26 Done. I think it is no problem.
```dart
  port.readOnListenFunction = (value) {
    print(value);
  };
  Future.delayed(Duration(seconds: 4)).then(
      (value) => port.readBytesOnListen(2, (value) => print('object$value')));
```

**Comment by sabin26** [comment]
If only we could do `serialPort.BytesToRead` that gives the received buffer size then the simplest solution would be the following:

```dart
main() {
  .....
  serialPort.OnDataReceived = OnDataReceivedFromSerialDevice;
  serialPort.Open();
}

OnDataReceivedFromSerialDevice() {
 // showing byte[] instead of Uint8List only for demo
  byte[] buffer = new byte[_serialPort.BytesToRead]; // this will be very helpful
  _serialPort.Read(buffer, 0, buffer.Length); // read the data ourselves
  ......
  do something with the data 
  ......
}
```

Here, the `OnDataReceivedFromSerialDevice` will only be called if the data is received and will not read any data. We will call the `serialPort.Read()` on our own.
Or,
You could do the same from the inside code and return the buffer as Uint8List after doing as shown in the code above.
Either approach is good.

@FengChendian  What do you think ?

**Comment by sabin26** [comment]
@FengChendian  If the idea was good enough and there is no other blocking factor besides this strange bug we could open up an issue on win32 package and get help to implement the `bytesToRead` properly. As per my understanding, if this is implemented correctly the feature as I described will be completed right ?
