### ISSUE TITLE
Hello, there is an error message when disconnecting the serial port.

### ISSUE THREAD

**Issue by qq1100** [FengChendian/serial_port_win32#39]
port.isOpened=true，When the serial port is disconnected, the log keeps looping out 。How to handle it? Thank you
Exception: \\.\COM8 is disconnected, win32 Error Code is 5
Exception: ClearCommError failed, win32 error code is 6
                       #0      SerialPort._getDataSizeInQueue (package:serial_port_win32/src/serial_port.dart:496:7)
                       #1      SerialPort.readBytes.<anonymous closure> (package:serial_port_win32/src/serial_port.dart:537:27)
                       #2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
                       #3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
                       #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by qq1100** [comment]
dart code:Timer.periodic(const Duration(microseconds: 500), (timer) async {
        Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));

**Comment by FengChendian** [comment]
> dart code: Timer.periodic(const Duration(microseconds: 500), (timer) async { Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));

- Why do you set periodic duration larger than read timeout？
   - The periodic callback is invoked repeatedly with duration intervals until canceled with the [cancel](https://api.dart.dev/stable/2.16.1/dart-async/Timer/cancel.html) function.

You can use try catch like:
```dart
Timer.periodic(const Duration(seconds: 2), (timer) {
try {
  Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));
} on Exception {
  timer.cancel();
}
});
```

**Comment by qq1100** [comment]
你好，我这边还是

> > dart 代码： Timer.periodic（const Duration（微秒： 500），（timer）async { Uint8List unList = await port.readBytes（200，timeout：const Duration（微秒： 1000））；
> 
> * 为什么设置的周期持续时间小于读取超时时间？很奇怪。因为定时器应该在读取完成后处理。
>   
>   * 定期回调会按照持续时间间隔重复调用，直到使用[取消](https://api.dart.dev/stable/2.16.1/dart-async/Timer/cancel.html)函数取消。
> 
> 你可以使用 try catch 如下：
> 
> ```dart
> Timer.periodic(const Duration(seconds: 2), (timer) {
> try {
>   Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));
> } on Exception {
>   timer.cancel();
> }
> });
> ```
> 
> 更多信息请参阅https://dart.dev/language/error-handling

你好，我改了周期持续时间后，再加上on Exception还是会出现报错，报错后整个页面卡住无法操作。日志里面一直打印报错信息。

**Comment by qq1100** [comment]
> 你好，我这边还是
> 
> > > dart 代码： Timer.periodic（const Duration（微秒： 500），（timer）async { Uint8List unList = wait port.readBytes（200，超时：const Duration（微秒： 1000））；
> > 
> > 
> > 
> > * 为什么设置的周期持续时间小于读取超时时间？很奇怪。因为定时器应该在读取完成后处理。
> >   
> >   * 定期回调会按照持续时间间隔重复调用，直到使用[取消](https://api.dart.dev/stable/2.16.1/dart-async/Timer/cancel.html)函数取消。
> > 
> > 你可以使用 try catch 如下：
> > ```dart
> > Timer.periodic(const Duration(seconds: 2), (timer) {
> > try {
> >   Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));
> > } on Exception {
> >   timer.cancel();
> > }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更多信息请参阅https://dart.dev/language/error-handling
> 
> 你好，我修改了周期持续时间后，再加上异常还是会出现报错，报错后整个页面卡住无法操作。日志里面一直打印报错信息。

周期循环时间越短对我很重要，因为我需要实时监听串口数据。如果把周期时间改成秒的话就没法做到实时抓取硬件回复的信息了。或者有没有其他方法可以实时获取到串口回复的信息？谢谢你

**Comment by FengChendian** [comment]
> 你好，我这边还是
> 
> > > dart 代码： Timer.periodic（const Duration（微秒： 500），（timer）async { Uint8List unList = await port.readBytes（200，timeout：const Duration（微秒： 1000））；
> > 
> > 
> > 
> > * 为什么设置的周期持续时间小于读取超时时间？很奇怪。因为定时器应该在读取完成后处理。
> >   
> >   * 定期回调会按照持续时间间隔重复调用，直到使用[取消](https://api.dart.dev/stable/2.16.1/dart-async/Timer/cancel.html)函数取消。
> > 
> > 你可以使用 try catch 如下：
> > ```dart
> > Timer.periodic(const Duration(seconds: 2), (timer) {
> > try {
> >   Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));
> > } on Exception {
> >   timer.cancel();
> > }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 更多信息请参阅https://dart.dev/language/error-handling
> 
> 你好，我改了周期持续时间后，再加上on Exception还是会出现报错，报错后整个页面卡住无法操作。日志里面一直打印报错信息。 try { timer = Timer.periodic(const Duration(microseconds: 1000), (timer) async { Uint8List unList = await port.readBytes(200, timeout: const Duration( microseconds: 500)); }); }on Exception{ LogUtils().e("Exception1111"); timer!.cancel(); }

你的报错和之前一样吗？

你代码其实存在一个严重问题

你读取了200字节，但你延迟给的是500us，并且timer的周期是1000us，这意味着如果超时，你最多只有500us的时间执行read函数，但这可能是读不完的.即使你给1000us也可能读不完，（因为一般情况下，Windows时间片精度应该只能到15ms）。如果没有执行完最后的timer.cancel，这会导致timer创建新的历程，从而不能关闭timer。

比如下面的这段代码，timer是无法关闭的，因为print执行的太慢了没有执行到cancel就有了新的周期。
```dart
Future<void> justPrint() async {
  
  print("1213");
  await Future.delayed(Duration(seconds: 2));
}

void main() async {


  Timer.periodic(Duration(seconds: 1), (timer) async {
    print("object");
    await justPrint();
    timer.cancel();
  });

  while (true) {
    await Future.delayed(Duration(seconds: 10));
  }
}
```

**Comment by qq1100** [comment]
> > 你好，我这边还是
> > > > dart 代码： Timer.periodic（const Duration（微秒： 500），（timer）async { Uint8List unList = wait port.readBytes（200，超时：const Duration（微秒： 1000））；
> > > 
> > > 
> > > 
> > > * 为什么设置的周期持续时间小于读取超时时间？很奇怪。因为定时器应该在读取完成后处理。
> > >   
> > >   * 定期回调会按照持续时间间隔重复调用，直到使用[取消](https://api.dart.dev/stable/2.16.1/dart-async/Timer/cancel.html)函数取消。
> > > 
> > > 你可以使用 try catch 如下：
> > > ```dart
> > > Timer.periodic(const Duration(seconds: 2), (timer) {
> > > try {
> > >   Uint8List unList = await port.readBytes(200, timeout: const Duration(microseconds: 1000));
> > > } on Exception {
> > >   timer.cancel();
> > > }
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 更多信息请参阅https://dart.dev/language/error-handling
> > 
> > 
> > 你好，我修改了周期持续时间后，再加上异常还是会出现报错，报错后整个页面卡住无法操作。日志里面一直打印报错信息。 try {timer = Timer.periodic(const Duration(microseconds: 1000), (定时器) async { Uint8List unList = wait port.readBytes(200, 超时: const Duration( 微秒: 500)); }关于异常{ LogUtils().e("Exception1111");计时器！.cancel(); }
> 
> 你的报错和之前一样吗？
> 
> **你代码其实存在一个严重的问题**
> 
> 你读取了200字节，但你超时给的是500us，而定时器的周期是1000us，这意味着如果超时，你最多只有500us的时间执行读取函数，但即使你可能是读不完的。给1000us也可以读不完，（因为一般情况下，Windows时间片应该默认1ms，甚至老设备可能是15ms）。如果没有执行完最后的timer.cancel，这会导致timer创建新的过程，从而无法关闭timer。
> 
> 比如说的代码，定时器是无法直接关闭的，因为打印执行的太慢了没有执行到取消了新的。周期在我的电脑上，定时器被执行了三遍
> 
> ```dart
> Future<void> justPrint() async {
>   
>   print("1213");
>   await Future.delayed(Duration(seconds: 2));
> }
> 
> void main() async {
> 
> 
>   Timer.periodic(Duration(seconds: 1), (timer) async {
>     print("object");
>     await justPrint();
>     timer.cancel();
>   });
> 
>   while (true) {
>     await Future.delayed(Duration(seconds: 10));
>   }
> }
> ```
> 
> 另外，Windows默认对读取函数的超时也有默认处理，单位我没错记的话只能是ms。所以不要期待你能在最多串口设备上或者us级精度。
> 
> ```c++
> typedef struct _COMMTIMEOUTS {
>   DWORD ReadIntervalTimeout;
>   DWORD ReadTotalTimeoutMultiplier;
>   DWORD ReadTotalTimeoutConstant;
>   DWORD WriteTotalTimeoutMultiplier;
>   DWORD WriteTotalTimeoutConstant;
> } COMMTIMEOUTS, *LPCOMMTIMEOUTS;
> ```
> 
> 你最起码应该保证有几ms甚至几十ms的裕度去读取200个字节（具体多大裕度可能和设备性能有关，而且你应该是debug模式运行的吧，裕度可能需要更大）另外保证dart的VM并不能保证实时性（甚至普通的Windows操作系统也不能保证），你不能通过这种方式来保证实时性。
> 
> * 如果您只是希望能够达到实时性，您完全可以将采样周期放宽到例如 50/100ms 这样。
> * 或者你应该使用**明确的顺序**的异步执行，例如在while循环里读取+await让出执行权+判断读取结果，或者是使用stream。
> * Timer.periodic内部不应该去干一些特别运行且会互相影响的操作
> * 如果你真的想要我们级的实时性，你不应该使用普通的Windows，你首先应该使用带有实时内核的Windows（大概是企业版的一个功能）Linux或者或者嵌入式系统，不过dart此时可以实现保证实时性我不太清楚。

分析的很详细，谢谢。打开串口收发信息没问题，只有在通讯结束后。断开连接才会出现这个问题，很容易复现。有没有其他方法避免错误提示？我试过while去执行断开设备后也是会出现这个报错。有没有技术交流群，可以及时沟通。

**Comment by FengChendian** [comment]
@qq1100 

- 报错或者说exception本身是刻意设计的，因为用户需要知道库是否在正常执行，在读取发生错误时抛出异常（断连会导致`ClearCommError`函数异常，在win32中被定义为error）是常见操作。如果我在库代码中不抛出这个异常，用户代码可能会产生非预期结果而无任何提示。（当然，我或许可以加个选项抑制所有异常）。
- 你要做的且理论上在dart中仅能做的其实就是捕获异常并处理它，dart是极度鼓励你用try catch和throw的，而不是抑制exception。不过你如果在while中做这个事情，应该只需要catch一次，不像timer.periodic里可能出现问题。

PS: 非主动断开连接一般是exception，这在python的`pyserial`上应该也是这么做的。

至于群的话确实没有，我可以考虑建一个，但dart用的人不多感觉没啥必要 😢

**Comment by qq1100** [comment]
> @qq1100
> 
> * 报错或者说exception本身是刻意设计的，因为用户需要知道库是否在正常执行，在读取发生错误时抛出异常（断连会导致`ClearCommError`函数异常，在win32中被定义为error）是常见操作。如果我在库代码中不抛出这个异常，用户代码可能会产生非预期结果而无任何提示。（当然，我或许可以加个选项抑制所有异常）。
> * 你要做的且理论上在dart中仅能做的其实就是捕获异常并处理它，dart是极度鼓励你用try catch和throw的，而不是抑制exception。不过你如果在while中做这个事情，应该只需要catch一次并break，不像timer.periodic里可能出现问题。
> 
> PS: 非主动断开连接一般是exception，这在python的`pyserial`上应该也是这么做的。
> 
> 至于群的话确实没有，我可以考虑建一个，但dart用的人不多感觉好像没啥必要

谢谢，我再尝试下。

**Comment by FengChendian** [comment]
> > @qq1100
> > 
> > * 报错或者说exception本身是刻意设计的，因为用户需要知道库是否在正常执行，在读取发生错误时抛出异常（断连会导致`ClearCommError`函数异常，在win32中被定义为error）是常见操作。如果我在库代码中不抛出这个异常，用户代码可能会产生非预期结果而无任何提示。（当然，我或许可以加个选项抑制所有异常）。
> > * 你要做的且理论上在dart中仅能做的其实就是捕获异常并处理它，dart是极度鼓励你用try catch和throw的，而不是抑制exception。不过你如果在while中做这个事情，应该只需要catch一次并break，不像timer.periodic里可能出现问题。
> > 
> > PS: 非主动断开连接一般是exception，这在python的`pyserial`上应该也是这么做的。
> > 至于群的话确实没有，我可以考虑建一个，但dart用的人不多感觉好像没啥必要
> 
> 谢谢，我再尝试下。

稍等，等我更新下版本，我觉得你这样的需求和我里面用的timer也有可能冲突，我改下结构。

**Comment by qq1100** [comment]
> > > @qq1100
> > > 
> > > * 报错或者说exception本身是刻意设计的，因为用户需要知道库是否在正常执行，在读取发生错误时抛出异常（断连会导致`ClearCommError`函数异常，在win32中被定义为error）是常见操作。如果我在库代码中不抛出这个异常，用户代码可能会产生非预期结果而无任何提示。（当然，我或许可以加个选项抑制所有异常）。
> > > * 你要做的且理论上在dart中仅能做的其实就是捕获异常并处理它，dart是极度鼓励你用try catch和throw的，而不是抑制exception。不过你如果在while中做这个事情，应该只需要catch一次并break，不像timer.periodic里可能出现问题。
> > > 
> > > PS: 非主动断开连接一般是exception，这在python的`pyserial`上应该也是这么做的。
> > > 至于群的话确实没有，我可以考虑建一个，但dart用的人不多感觉好像没啥必要
> > 
> > 
> > 谢谢，我再尝试下。
> 
> 稍等，等我更新下版本，我觉得你这样的需求和我里面用的timer也有可能冲突，我改下结构。我应该可以保证你任何情况下只触发一次异常。

好的，好的。万分感谢。。

**Comment by FengChendian** [comment]
@qq1100 

我更新了`2.1.11`，现在应该能确保只有一个exception而且你能catch的到它。

这是我的测试代码

```dart
    /// Test disconnected
    while (true) {
      try {
        await port.readBytes(1, timeout: Duration(seconds: 1));
      } catch (e) {
        print(e);
        break;
      }
    }
```

![image](https://github.com/user-attachments/assets/0b5707f0-3dd8-49d4-a2d8-5753b7898680)

**Comment by qq1100** [comment]
> @qq1100
> 
> 我更新了`2.1.11`，现在应该能够确保只有一个异常并且你能够捕获到它。
> 
> 这是我测试的代码
> 
> ```dart
>     /// Test disconnected
>     while (true) {
>       try {
>         await port.readBytes(1, timeout: Duration(seconds: 1));
>       } catch (e) {
>         print(e);
>         break;
>       }
>     }
> ```
> 
> ![图像](https://private-user-images.githubusercontent.com/37545115/390670887-0b5707f0-3dd8-49d4-a2d8-5753b7898680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzY3NzksIm5iZiI6MTczMjc3NjQ3OSwicGF0aCI6Ii8zNzU0NTExNS8zOTA2NzA4ODctMGI1NzA3ZjAtM2RkOC00OWQ0LWEyZDgtNTc1M2I3ODk4NjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDg3YmZmNDFmY2ZmNzFhMTFhM2M0YTAyOTIyM2IwZjRlODljMzhhNWE3N2IzMTMzZTdhNDY2OTE3ZjVmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1KpAk1SxVFErswMcbPdqbl_-IXZqtOXtY5FVuc_5Rk)

OK,OK.我立马去试试。

**Comment by FengChendian** [comment]
> > > @qq1100
> > > 我更新了`2.1.11`，现在应该能够确保只有一个异常并且你能够捕获到它。
> > > 这是我的商业
> > > ```dart
> > >     /// Test disconnected
> > >     while (true) {
> > >       try {
> > >         await port.readBytes(1, timeout: Duration(seconds: 1));
> > >       } catch (e) {
> > >         print(e);
> > >         break;
> > >       }
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![图像](https://private-user-images.githubusercontent.com/37545115/390670887-0b5707f0-3dd8-49d4-a2d8-5753b7898680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzY3NzksIm5iZiI6MTczMjc3NjQ3OSwicGF0aCI6Ii8zNzU0NTExNS8zOTA2NzA4ODctMGI1NzA3ZjAtM2RkOC00OWQ0LWEyZDgtNTc1M2I3ODk4NjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDg3YmZmNDFmY2ZmNzFhMTFhM2M0YTAyOTIyM2IwZjRlODljMzhhNWE3N2IzMTMzZTdhNDY2OTE3ZjVmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1KpAk1SxVFErswMcbPdqbl_-IXZqtOXtY5FVuc_5Rk)
> > 
> > 
> > 好的，好的。我去试试。
> 
> Because le_pc depends on serial_port_win32 ^2.1.11 which doesn't match any versions, version solving failed.
> 
> You can try the following suggestion to make the pubspec resolve:
> 
> * Consider downgrading your constraint on serial_port_win32: flutter pub add serial_port_win32:^2.1.10，无法升级？？


你用了中国大陆镜像？那需要等一等同步，大约一小时同步一次吧

**Comment by qq1100** [comment]
> > > > @qq1100
> > > > 我更新了`2.1.11`，现在应该能够确保只有一个异常并且你能够捕获到它。
> > > > 这是我的商业
> > > > ```dart
> > > >     /// Test disconnected
> > > >     while (true) {
> > > >       try {
> > > >         await port.readBytes(1, timeout: Duration(seconds: 1));
> > > >       } catch (e) {
> > > >         print(e);
> > > >         break;
> > > >       }
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ![图像](https://private-user-images.githubusercontent.com/37545115/390670887-0b5707f0-3dd8-49d4-a2d8-5753b7898680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzY3NzksIm5iZiI6MTczMjc3NjQ3OSwicGF0aCI6Ii8zNzU0NTExNS8zOTA2NzA4ODctMGI1NzA3ZjAtM2RkOC00OWQ0LWEyZDgtNTc1M2I3ODk4NjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDg3YmZmNDFmY2ZmNzFhMTFhM2M0YTAyOTIyM2IwZjRlODljMzhhNWE3N2IzMTMzZTdhNDY2OTE3ZjVmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1KpAk1SxVFErswMcbPdqbl_-IXZqtOXtY5FVuc_5Rk)
> > > 
> > > 
> > > 好的，好的。我去试试。
> > 
> > 
> > Because le_pc depends on serial_port_win32 ^2.1.11 which doesn't match any versions, version solving failed.
> > You can try the following suggestion to make the pubspec resolve:
> > 
> > * Consider downgrading your constraint on serial_port_win32: flutter pub add serial_port_win32:^2.1.10，无法升级？？
> 
> 你用了中国大陆镜像？那需要等一等同步，大约一小时同步一次吧

对的，稍等我再尝试下。

**Comment by qq1100** [comment]
> > > > @qq1100
> > > > 我更新了`2.1.11`，现在应该能够确保只有一个异常并且你能够捕获到它。
> > > > 这是我的商业
> > > > ```dart
> > > >     /// Test disconnected
> > > >     while (true) {
> > > >       try {
> > > >         await port.readBytes(1, timeout: Duration(seconds: 1));
> > > >       } catch (e) {
> > > >         print(e);
> > > >         break;
> > > >       }
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ![图像](https://private-user-images.githubusercontent.com/37545115/390670887-0b5707f0-3dd8-49d4-a2d8-5753b7898680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NzY3NzksIm5iZiI6MTczMjc3NjQ3OSwicGF0aCI6Ii8zNzU0NTExNS8zOTA2NzA4ODctMGI1NzA3ZjAtM2RkOC00OWQ0LWEyZDgtNTc1M2I3ODk4NjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDA2NDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDg3YmZmNDFmY2ZmNzFhMTFhM2M0YTAyOTIyM2IwZjRlODljMzhhNWE3N2IzMTMzZTdhNDY2OTE3ZjVmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t1KpAk1SxVFErswMcbPdqbl_-IXZqtOXtY5FVuc_5Rk)
> > > 
> > > 
> > > 好的，好的。我去尝试一下。
> > 
> > 
> > 由于 le_pc 依赖于 serial_port_win32 ^2.1.11，而该版本不匹配任何版本，因此版本解析失败。
> > 您可以尝试以下建议来使 pubspec 解析：
> > 
> > * 考虑降级你对serial_port_win32的约束： flutter pub add serial_port_win32:^2.1.10，无法升级？
> 
> 你用了中国大陆镜像？那需要等一等同步，大约一小时同步一次吧

完美解决，感谢。
