### ISSUE TITLE
Port.onClose method

### ISSUE THREAD

**Issue by hamidjalili59** [FengChendian/serial_port_win32#5]
Hi 👋☺️
I want the port to close when the USB is disconnected and the onClose method to run. Is it possible? 🌹

Currently, when the USB is disconnected from the device, the library will no longer work until the software is restarted.

**Comment by FengChendian** [comment]
Do you mean that you unplugged the USB device directly? It causes  _isOpened == True in instance. I'm not sure if it is feasible  to close port and then reopen it. I don't have Serial Port to test now.

And for that, I will add a method for setting _isOpened status.

**Comment by FengChendian** [comment]
> 
> 
> Do you mean that you unplugged the USB device directly? It causes _isOpened == True in instance. I'm not sure if it is feasible to close port and then reopen it. I don't have Serial Port to test now.
> 
> And for that, I will add a method for setting _isOpened status.

I checked my small project in https://github.com/FengChendian/SerialPortTool . I found that you can read data successfully if you close port and reopen it.

About **onClose** method, I'm reading doc in https://docs.microsoft.com/en-us/windows/win32/devio/monitoring-communications-events. I think it can be implemented. Now you can close it and reopen.

**Comment by hamidjalili59** [comment]
Oh yes, thank you, I will definitely test it tomorrow

**Comment by hamidjalili59** [comment]
![Screenshot 2021-08-01 124001](https://user-images.githubusercontent.com/42936283/127764219-6a869e2b-907b-4839-8716-8dfe80a33284.png)
Hi
It does not sense disconnection at all

**Comment by hamidjalili59** [comment]
Thanks I think I fixed it

**Comment by FengChendian** [comment]
> ![Screenshot 2021-08-01 124001](https://user-images.githubusercontent.com/42936283/127764389-236cd206-538d-4dce-8c99-6ebb6a1a16a9.png)
> 
> Hi
> It does not sense disconnection at all

This library don't know whether port is connected or disconnected. I will try to implement auto close when win32 package update createEvent function.

So if you want to know disconnection, I think you can compare with available ports.

**Comment by hamidjalili59** [comment]
I fixed it
TY ♥
