### ISSUE TITLE
no data after closing and reopening connection

### ISSUE THREAD

**Issue by ali80** [FengChendian/serial_port_win32#8]
Hi, 
Connecting works the first time and I receive data after connection,
after closing connection and trying to connect again,   no data is received on the new conenction
```dart
ElevatedButton(
    onPressed: () async {
      sp = SerialPort("COM9", openNow: true);
      sp.readBytesOnListen(8, (value) {
        print(value.toString());
      });
    },
    child: Text("connect")),
ElevatedButton(
    onPressed: () async {
      sp.close();
    },
    child: Text("disconnect")),

```

**Comment by FengChendian** [comment]
Because this is **Singleton Pattern**. `sp = SerialPort("COM9", openNow: true);` only using once actually. If you print `sp.isOpened`, you will find value is false.
So don't re-create intsance. You can:
```dart
final sp = SerialPort("COM9", openNow: false);
ElevatedButton(
    onPressed: () async {
      sp.open()
      sp.readBytesOnListen(8, (value) {
        print(value.toString());
      });
    },
    child: Text("connect")),
```
or
```dart
ElevatedButton(
    onPressed: () async {
      sp = SerialPort("COM9", openNow: true);
      if (!sp.isOpened) {
        sp.open()
      }
      sp.readBytesOnListen(8, (value) {
        print(value.toString());
      });
    },
    child: Text("connect")),
```

**Comment by ali80** [comment]
I used your second method and it works, thanks, 
but this seems weird, if I need multiple connections to multiple serial ports, you create multiple singletons for each port and then `SerialPort` factory use caching to return selected port?

**Comment by FengChendian** [comment]
> 
> 
> I used your second method and it works, thanks,
> but this seems weird, if I need multiple connections to multiple serial ports, you create multiple singletons for each port and then `SerialPort` factory uses caching to return selected port's instance?

Yeah... It is weird. Because I found that if I don't use singleton, Hot reload will cause multiple connection problems for same COM name.

**Comment by ali80** [comment]
Interesting to know reasoning behind that, maybe add example to the docs since this kind of usage is not obvious
