### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Lyazz** [FengChendian/serial_port_win32#9]
Why in the pub page of the package it is mentionned that it is compatible with all except web, but in reality it is only compatible with windows ??

**Comment by FengChendian** [comment]
It's due to win32 package and flutter packages generation rules. If you write a Windows package with win32 package, pub displays that it's compatible with all platform...

**Comment by Lyazz** [comment]
Thanks for clarifying this and thank you for this awesome library <3
